Resources:
  # Projection Table
  ProjectionTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: "${file(./${opt:stage}.yml):tableName}-projection"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: partitionKey
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: gsi1PartitionKey
          AttributeType: S
        - AttributeName: gsi1SortKey
          AttributeType: S
      KeySchema:
        - AttributeName: partitionKey
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: type
          KeySchema:
            - AttributeName: type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1PartitionKey
              KeyType: HASH
            - AttributeName: gsi1SortKey
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Internal Events Table
  InternalEventsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: "${file(./${opt:stage}.yml):tableName}-internal-events"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE